version: '3.8'

services:
  # Main application
  finance-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL:-}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-finance_db}
      - POSTGRES_USER=${POSTGRES_USER:-finance_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-finance_password}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-finance_db}
      - MYSQL_USER=${MYSQL_USER:-finance_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-finance_password}
      - SQLITE_DATABASE_PATH=${SQLITE_DATABASE_PATH:-./data/finance.db}
      - SESSION_SECRET=${SESSION_SECRET:-finance-app-secret-key-change-in-production}
    volumes:
      # Mount data directory for persistent storage (SQLite, configs, etc.)
      - finance-data:/app/data
    depends_on:
      - postgres
      - mysql
    restart: unless-stopped
    networks:
      - finance-network

  # PostgreSQL database (optional - use if not using Supabase)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-finance_db}
      - POSTGRES_USER=${POSTGRES_USER:-finance_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-finance_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Initialize database with schema if needed
      - ../database-setup/supabase-setup.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - finance-network

  # MySQL database (optional - alternative to PostgreSQL)
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-finance_db}
      - MYSQL_USER=${MYSQL_USER:-finance_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-finance_password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - finance-network
    command: --default-authentication-plugin=mysql_native_password
  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - finance-network
    command: redis-server --appendonly yes

volumes:
  finance-data:
    driver: local
  postgres-data:
    driver: local
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  finance-network:
    driver: bridge